### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by VAZaitesev** [flugg/laravel-responder#187]
It looks like there is some problems with illuminate/contracts  dependencies
![image](https://user-images.githubusercontent.com/94828591/218954233-ad8c7303-6ad3-48be-badf-7ec107bf6f00.png)

**Comment by jackkitley** [comment]
yes please.

**Comment by Ahmard** [comment]
Facing same issue here too.
![Screenshot from 2023-02-19 20-51-05](https://user-images.githubusercontent.com/44737217/219971674-87ef6283-4ccc-4201-b4cb-433ffef9c379.png)

**Comment by Bjaskular** [comment]
Hello everyone, I have the same problem:
**composer.json**:

> {
>     "name": "laravel/laravel",
>     "type": "project",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "require": {
>         "php": "^8.1",
>         "guzzlehttp/guzzle": "^7.2",
>         "laravel/framework": "^10.0",
>         "laravel/sanctum": "^3.2",
>         "laravel/tinker": "^2.8"
>     },
>     "require-dev": {
>         "fakerphp/faker": "^1.9.1",
>         "laravel/pint": "^1.0",
>         "laravel/sail": "^1.18",
>         "mockery/mockery": "^1.4.4",
>         "nunomaduro/collision": "^7.0",
>         "phpunit/phpunit": "^10.0",
>         "spatie/laravel-ignition": "^2.0"
>     },
>     "autoload": {
>         "psr-4": {
>             "App\\": "app/",
>             "Database\\Factories\\": "database/factories/",
>             "Database\\Seeders\\": "database/seeders/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "scripts": {
>         "post-autoload-dump": [
>             "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
>             "@php artisan package:discover --ansi"
>         ],
>         "post-update-cmd": [
>             "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
>         ],
>         "post-root-package-install": [
>             "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "@php artisan key:generate --ansi"
>         ]
>     },
>     "extra": {
>         "laravel": {
>             "dont-discover": []
>         }
>     },
>     "config": {
>         "optimize-autoloader": true,
>         "preferred-install": "dist",
>         "sort-packages": true,
>         "allow-plugins": {
>             "pestphp/pest-plugin": true,
>             "php-http/discovery": true
>         }
>     },
>     "minimum-stability": "stable",
>     "prefer-stable": true
> }

**Error**:
![image](https://user-images.githubusercontent.com/63540680/221173997-9a4fb1df-3822-4fd1-8c5d-d628d8e3aac8.png)

**PHP version**: PHP 8.1.2-1ubuntu2.8 (cli)

**Comment by Ahmard** [comment]
Thank you for the fix!

**Comment by Bjaskular** [comment]
I thank you as well 😄

**Comment by flugg** [comment]
> I thank you as well 😄

Really appreciate the donation ❤️
