### ISSUE TITLE
composer require flugger/laravel-responder error laravel 10

### ISSUE THREAD

**Issue by jackkitley** [flugg/laravel-responder#188]
`
In OverridesFractal.php line 22:

  Declaration of Flugg\Responder\Transformers\Concerns\OverridesFractal::getAvailableIncludes() must be compatible with League\Fractal\TransformerAbstract::getAvailableIncludes(): array

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255`

**Comment by aVyarvelsky** [comment]
As a temporal measure, I've added 
```
"league/fractal": "0.19.0"
```
To root composer.json, if has downgraded this package and everything seems fine for now.

**Comment by UtkuDalmaz** [comment]
> As a temporal measure, I've added
> 
> ```
> "league/fractal": "0.19.0"
> ```
> 
> To root composer.json, if has downgraded this package and everything seems fine for now.

thanks but this repo should be updated to support laravel 10 asap tho

**Comment by aVyarvelsky** [comment]
Let's wait for https://github.com/flugg/laravel-responder/pull/190

**Comment by flugg** [comment]
#190 is merged, apologises for the wait
