### ISSUE TITLE
Flugg\Responder\Serializers\NoopSerializer error for method null

### ISSUE THREAD

**Issue by jackkitley** [flugg/laravel-responder#201]
Got this error today. Not sure if it has been fixed somewhere?

Thanks

`    "class": "TypeError",
    "message": "Flugg\\Responder\\Serializers\\NoopSerializer::null(): Return value must be of type array, null returned",`

![Screenshot 2023-10-16 at 19 49 06](https://github.com/flugg/laravel-responder/assets/3243014/4e4ceded-5e82-4af0-aa67-cebaabe9c2a9)

**Comment by wahlmika** [comment]
Any updates on this. We are having an issue with this also in our production environment?

**Comment by ossycodes** [comment]
fixes https://github.com/flugg/laravel-responder/pull/202

**Comment by flugg** [comment]
Should be fixed now. Sorry for the late response. Let me know if you're still having issues!
