### ISSUE TITLE
Laravel 11

### ISSUE THREAD

**Issue by UtkuDalmaz** [flugg/laravel-responder#204]
Problem 1
    - Conclusion: don't install flugger/laravel-responder v3.3.1 (conflict analysis result)
    - illuminate/contracts[v5.6.0, ..., 5.8.x-dev] require php ^7.1.3 -> your php version (8.3.3) does not satisfy that requirement.
    - illuminate/contracts[v6.0.0, ..., v6.19.1] require php ^7.2 -> your php version (8.3.3) does not satisfy that requirement.
    - illuminate/contracts[v7.0.0, ..., v7.28.4] require php ^7.2.5 -> your php version (8.3.3) does not satisfy that requirement.
    - illuminate/contracts[v8.0.0, ..., v8.11.2] require php ^7.3 -> your php version (8.3.3) does not satisfy that requirement.
    - Root composer.json requires flugger/laravel-responder ^3.3.0 -> satisfiable by flugger/laravel-responder[v3.3.0, v3.3.1].
    - Conclusion: don't install laravel/framework v11.0.1 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.2 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.3 (conflict analysis result)
    - Conclusion: don't install laravel/framework v11.0.0 (conflict analysis result)
    - flugger/laravel-responder v3.3.0 requires illuminate/contracts ^5.1|^6.0|^7.0|^8.0|^9.0|^10.0 -> satisfiable by illuminate/contracts[v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev].
    - Only one of these can be installed: illuminate/contracts[dev-master, v5.1.1, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev, v11.0.0, ..., 11.x-dev], laravel/framework[v11.0.0, ..., 11.x-dev]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - Root composer.json requires laravel/framework ^11.0.0 -> satisfiable by laravel/framework[v11.0.0, ..., 11.x-dev].

I am having this when I want to upgrade to laravel 11

**Comment by flugg** [comment]
Tagged a v3.4.0 now that should include Laravel 11 support. Let me know if it doesn't work
